x-app-volumes: &app-volumes
  - ./app:/app/app
  - ./migrations:/app/migrations

services:
  adserv:
    build: .
    ports:
      - "8000:8000"
    command: uv run uvicorn app.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    environment:
      - DB__HOST=db
      - DB__USER=${POSTGRES_USER}
      - DB__PASSWORD=${POSTGRES_PASSWORD}
      - DB__NAME=${POSTGRES_DB}
      - LOG__LEVEL=DEBUG
      - LOG__FORMAT=json
      - ENV=docker
    depends_on:
      db:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully
    volumes: *app-volumes

  migrate:
    build: .
    command: uv run alembic upgrade head
    env_file:
      - .env
    environment:
      - DB__HOST=db
      - DB__USER=${POSTGRES_USER}
      - DB__PASSWORD=${POSTGRES_PASSWORD}
      - DB__NAME=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes: *app-volumes

  db:
    image: postgres:18
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
