services:
  adserv:
    build: .
    ports:
      - "8000:8000"
    command: uv run uvicorn app.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - .git
            - .venv
            - __pycache__
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:18
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1m
      timeout: 20s
      retries: 3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
