"""initial

Revision ID: 58f9779e1c23
Revises:
Create Date: 2026-09-09 15:05:40.843537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58f9779e1c23"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advertiser",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advertiser")),
    )
    op.create_table(
        "campaign",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("advertiser_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "archived",
                name="campaignstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("daily_budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("starts_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ends_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'paused'::character varying, 'archived'::character varying]::text[])",
            name=op.f("ck_campaign_valid_status"),
        ),
        sa.CheckConstraint(
            "daily_budget > 0", name=op.f("ck_campaign_daily_budget_positive")
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_campaign_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["advertiser_id"],
            ["advertiser.id"],
            name=op.f("fk_campaign_advertiser_id_advertiser"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign")),
    )
    op.create_index(
        op.f("ix_campaign_advertiser_id"), "campaign", ["advertiser_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_advertiser_id"), table_name="campaign")
    op.drop_table("campaign")
    op.drop_table("advertiser")
    # ### end Alembic commands ###
