"""initial

Revision ID: 8f95271268d0
Revises:
Create Date: 2026-09-09 13:55:33.562664

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8f95271268d0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
